// ItemTemplateRegistry.cs — auto-generated from Items.bb InitItemTemplates
// Regenerate: python agent-tools/gen_item_templates.py

namespace SCPCB360.GameLogic
{
    internal static class ItemTemplateRegistry
    {
        internal readonly struct Def
        {
            public string Name { get; init; }
            public string TempName { get; init; }
            public string ObjPath { get; init; }
            public string InvImgPath { get; init; }
            public string ImgPath { get; init; }
            public string ScaleExpr { get; init; }
            public string TexPath { get; init; }
            public int Sound { get; init; }
        }

        internal static readonly Def[] All =
        {
            new Def
            {
                Name = "Some SCP-420-J",
                TempName = "420",
                ObjPath = "GFX/items/420",
                InvImgPath = "GFX/items/INV420",
                ImgPath = "",
                ScaleExpr = "0.0005f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "Level 1 Key Card",
                TempName = "key1",
                ObjPath = "GFX/items/keycard",
                InvImgPath = "GFX/items/INVkey1",
                ImgPath = "",
                ScaleExpr = "0.0004f",
                TexPath = "GFX/items/keycard1",
                Sound = 2,
            },
            new Def
            {
                Name = "Level 2 Key Card",
                TempName = "key2",
                ObjPath = "GFX/items/keycard",
                InvImgPath = "GFX/items/INVkey2",
                ImgPath = "",
                ScaleExpr = "0.0004f",
                TexPath = "GFX/items/keycard2",
                Sound = 1,
            },
            new Def
            {
                Name = "Level 3 Key Card",
                TempName = "key3",
                ObjPath = "GFX/items/keycard",
                InvImgPath = "GFX/items/INVkey3",
                ImgPath = "",
                ScaleExpr = "0.0004f",
                TexPath = "GFX/items/keycard3",
                Sound = 1,
            },
            new Def
            {
                Name = "Level 4 Key Card",
                TempName = "key4",
                ObjPath = "GFX/items/keycard",
                InvImgPath = "GFX/items/INVkey4",
                ImgPath = "",
                ScaleExpr = "0.0004f",
                TexPath = "GFX/items/keycard4",
                Sound = 1,
            },
            new Def
            {
                Name = "Level 5 Key Card",
                TempName = "key5",
                ObjPath = "GFX/items/keycard",
                InvImgPath = "GFX/items/INVkey5",
                ImgPath = "",
                ScaleExpr = "0.0004f",
                TexPath = "GFX/items/keycard5",
                Sound = 1,
            },
            new Def
            {
                Name = "Playing Card",
                TempName = "misc",
                ObjPath = "GFX/items/keycard",
                InvImgPath = "GFX/items/INVcard",
                ImgPath = "",
                ScaleExpr = "0.0004f",
                TexPath = "GFX/items/card",
                Sound = 1,
            },
            new Def
            {
                Name = "Mastercard",
                TempName = "misc",
                ObjPath = "GFX/items/keycard",
                InvImgPath = "GFX/items/INVmastercard",
                ImgPath = "",
                ScaleExpr = "0.0004f",
                TexPath = "GFX/items/mastercard",
                Sound = 1,
            },
            new Def
            {
                Name = "Key Card Omni",
                TempName = "key6",
                ObjPath = "GFX/items/keycard",
                InvImgPath = "GFX/items/INVkeyomni",
                ImgPath = "",
                ScaleExpr = "0.0004f",
                TexPath = "GFX/items/keycardomni",
                Sound = 1,
            },
            new Def
            {
                Name = "SCP-860",
                TempName = "scp860",
                ObjPath = "GFX/items/key",
                InvImgPath = "GFX/items/INVkey",
                ImgPath = "",
                ScaleExpr = "0.001f",
                TexPath = "",
                Sound = 3,
            },
            new Def
            {
                Name = "Document SCP-079",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc079",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-895",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc895",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-860",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc860",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-860-1",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc8601",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "SCP-093 Recovered Materials",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc093rm",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-106",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc106",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Dr. Allok's Note",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc106_2",
                ScaleExpr = "0.0025f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Recall Protocol RP-106-N",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/docRP",
                ScaleExpr = "0.0025f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-682",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc682",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-173",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc173",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-372",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc372",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-049",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc049",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-096",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc096",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-008",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc008",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-012",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc012",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-500",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc500",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-714",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc714",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-513",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc513",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-035",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc035",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "SCP-035 Addendum",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc035ad",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-939",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc939",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-966",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc966",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-970",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc970",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-1048",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc1048",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-1123",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc1123",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-1162",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc1162",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-1499",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc1499",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Incident Report SCP-1048-A",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc1048a",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Drawing",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc1048",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Leaflet",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/leaflet",
                ScaleExpr = "0.003f",
                TexPath = "GFX/items/notetexture",
                Sound = 0,
            },
            new Def
            {
                Name = "Dr. L's Note",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVnote",
                ImgPath = "GFX/items/docL1",
                ScaleExpr = "0.0025f",
                TexPath = "GFX/items/notetexture",
                Sound = 0,
            },
            new Def
            {
                Name = "Dr L's Note",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVnote",
                ImgPath = "GFX/items/docL2",
                ScaleExpr = "0.0025f",
                TexPath = "GFX/items/notetexture",
                Sound = 0,
            },
            new Def
            {
                Name = "Blood-stained Note",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVnote",
                ImgPath = "GFX/items/docL3",
                ScaleExpr = "0.0025f",
                TexPath = "GFX/items/notetexture",
                Sound = 0,
            },
            new Def
            {
                Name = "Dr. L's Burnt Note",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVbn",
                ImgPath = "GFX/items/docL4",
                ScaleExpr = "0.0025f",
                TexPath = "GFX/items/BurntNoteTexture",
                Sound = 0,
            },
            new Def
            {
                Name = "Dr L's Burnt Note",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVbn",
                ImgPath = "GFX/items/docL5",
                ScaleExpr = "0.0025f",
                TexPath = "GFX/items/BurntNoteTexture",
                Sound = 0,
            },
            new Def
            {
                Name = "Scorched Note",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVbn",
                ImgPath = "GFX/items/docL6",
                ScaleExpr = "0.0025f",
                TexPath = "GFX/items/BurntNoteTexture",
                Sound = 0,
            },
            new Def
            {
                Name = "Journal Page",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/docGonzales",
                ScaleExpr = "0.0025f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Log #1",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/f4",
                ScaleExpr = "0.004f",
                TexPath = "GFX/items/f4",
                Sound = 0,
            },
            new Def
            {
                Name = "Log #2",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/f5",
                ScaleExpr = "0.004f",
                TexPath = "GFX/items/f4",
                Sound = 0,
            },
            new Def
            {
                Name = "Log #3",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/f6",
                ScaleExpr = "0.004f",
                TexPath = "GFX/items/f4",
                Sound = 0,
            },
            new Def
            {
                Name = "Strange Note",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVnote",
                ImgPath = "GFX/items/docStrange",
                ScaleExpr = "0.0025f",
                TexPath = "GFX/items/notetexture",
                Sound = 0,
            },
            new Def
            {
                Name = "Nuclear Device Document",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/docNDP",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Class D Orientation Leaflet",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/docORI",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Note from Daniel",
                TempName = "paper",
                ObjPath = "GFX/items/note",
                InvImgPath = "GFX/items/INVnote2",
                ImgPath = "GFX/items/docdan",
                ScaleExpr = "0.0025f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Burnt Note",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVbn",
                ImgPath = "GFX/items/bn",
                ScaleExpr = "0.003f",
                TexPath = "GFX/items/BurntNoteTexture",
                Sound = 0,
            },
            new Def
            {
                Name = "Mysterious Note",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVnote",
                ImgPath = "GFX/items/sn",
                ScaleExpr = "0.003f",
                TexPath = "GFX/items/notetexture",
                Sound = 0,
            },
            new Def
            {
                Name = "Mobile Task Forces",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/docMTF",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Security Clearance Levels",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/docSC",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Object Classes",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/docOBJC",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/docRAND3",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Addendum: 5/14 Test Log",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVnote",
                ImgPath = "GFX/items/docRAND2",
                ScaleExpr = "0.003f",
                TexPath = "GFX/items/notetexture",
                Sound = 0,
            },
            new Def
            {
                Name = "Notification",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVnote",
                ImgPath = "GFX/items/docRAND1",
                ScaleExpr = "0.003f",
                TexPath = "GFX/items/notetexture",
                Sound = 0,
            },
            new Def
            {
                Name = "Incident Report SCP-106-0204",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/docIR106",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Ballistic Vest",
                TempName = "vest",
                ObjPath = "GFX/items/vest",
                InvImgPath = "GFX/items/INVvest",
                ImgPath = "",
                ScaleExpr = "0.02f",
                TexPath = "GFX/items/Vest",
                Sound = 2,
            },
            new Def
            {
                Name = "Heavy Ballistic Vest",
                TempName = "finevest",
                ObjPath = "GFX/items/vest",
                InvImgPath = "GFX/items/INVvest",
                ImgPath = "",
                ScaleExpr = "0.022f",
                TexPath = "GFX/items/Vest",
                Sound = 2,
            },
            new Def
            {
                Name = "Bulky Ballistic Vest",
                TempName = "veryfinevest",
                ObjPath = "GFX/items/vest",
                InvImgPath = "GFX/items/INVvest",
                ImgPath = "",
                ScaleExpr = "0.025f",
                TexPath = "GFX/items/Vest",
                Sound = 2,
            },
            new Def
            {
                Name = "Hazmat Suit",
                TempName = "hazmatsuit",
                ObjPath = "GFX/items/hazmat",
                InvImgPath = "GFX/items/INVhazmat",
                ImgPath = "",
                ScaleExpr = "0.013f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "Hazmat Suit",
                TempName = "hazmatsuit2",
                ObjPath = "GFX/items/hazmat",
                InvImgPath = "GFX/items/INVhazmat",
                ImgPath = "",
                ScaleExpr = "0.013f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "Heavy Hazmat Suit",
                TempName = "hazmatsuit3",
                ObjPath = "GFX/items/hazmat",
                InvImgPath = "GFX/items/INVhazmat",
                ImgPath = "",
                ScaleExpr = "0.013f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "cup",
                TempName = "cup",
                ObjPath = "GFX/items/cup",
                InvImgPath = "GFX/items/INVcup",
                ImgPath = "",
                ScaleExpr = "0.04f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "Empty Cup",
                TempName = "emptycup",
                ObjPath = "GFX/items/cup",
                InvImgPath = "GFX/items/INVcup",
                ImgPath = "",
                ScaleExpr = "0.04f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "SCP-500-01",
                TempName = "scp500",
                ObjPath = "GFX/items/pill",
                InvImgPath = "GFX/items/INVpill",
                ImgPath = "",
                ScaleExpr = "0.0001f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "First Aid Kit",
                TempName = "firstaid",
                ObjPath = "GFX/items/firstaid",
                InvImgPath = "GFX/items/INVfirstaid",
                ImgPath = "",
                ScaleExpr = "0.05f",
                TexPath = "",
                Sound = 1,
            },
            new Def
            {
                Name = "Small First Aid Kit",
                TempName = "finefirstaid",
                ObjPath = "GFX/items/firstaid",
                InvImgPath = "GFX/items/INVfirstaid",
                ImgPath = "",
                ScaleExpr = "0.03f",
                TexPath = "",
                Sound = 1,
            },
            new Def
            {
                Name = "Blue First Aid Kit",
                TempName = "firstaid2",
                ObjPath = "GFX/items/firstaid",
                InvImgPath = "GFX/items/INVfirstaid2",
                ImgPath = "",
                ScaleExpr = "0.03f",
                TexPath = "GFX/items/firstaidkit2",
                Sound = 1,
            },
            new Def
            {
                Name = "Strange Bottle",
                TempName = "veryfinefirstaid",
                ObjPath = "GFX/items/eyedrops",
                InvImgPath = "GFX/items/INVbottle",
                ImgPath = "",
                ScaleExpr = "0.002f",
                TexPath = "GFX/items/bottle",
                Sound = 1,
            },
            new Def
            {
                Name = "Gas Mask",
                TempName = "gasmask",
                ObjPath = "GFX/items/gasmask",
                InvImgPath = "GFX/items/INVgasmask",
                ImgPath = "",
                ScaleExpr = "0.02f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "Gas Mask",
                TempName = "supergasmask",
                ObjPath = "GFX/items/gasmask",
                InvImgPath = "GFX/items/INVgasmask",
                ImgPath = "",
                ScaleExpr = "0.021f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "Heavy Gas Mask",
                TempName = "gasmask3",
                ObjPath = "GFX/items/gasmask",
                InvImgPath = "GFX/items/INVgasmask",
                ImgPath = "",
                ScaleExpr = "0.021f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "Origami",
                TempName = "misc",
                ObjPath = "GFX/items/origami",
                InvImgPath = "GFX/items/INVorigami",
                ImgPath = "",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Electronical components",
                TempName = "misc",
                ObjPath = "GFX/items/electronics",
                InvImgPath = "GFX/items/INVelectronics",
                ImgPath = "",
                ScaleExpr = "0.0011f",
                TexPath = "",
                Sound = 1,
            },
            new Def
            {
                Name = "Metal Panel",
                TempName = "scp148",
                ObjPath = "GFX/items/metalpanel",
                InvImgPath = "GFX/items/INVmetalpanel",
                ImgPath = "",
                ScaleExpr = "GameState.RoomScale",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "SCP-148 Ingot",
                TempName = "scp148ingot",
                ObjPath = "GFX/items/scp148",
                InvImgPath = "GFX/items/INVscp148",
                ImgPath = "",
                ScaleExpr = "GameState.RoomScale",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "S-NAV 300 Navigator",
                TempName = "nav",
                ObjPath = "GFX/items/navigator",
                InvImgPath = "GFX/items/INVnavigator",
                ImgPath = "GFX/items/navigator",
                ScaleExpr = "0.0008f",
                TexPath = "",
                Sound = 1,
            },
            new Def
            {
                Name = "S-NAV Navigator",
                TempName = "nav",
                ObjPath = "GFX/items/navigator",
                InvImgPath = "GFX/items/INVnavigator",
                ImgPath = "GFX/items/navigator",
                ScaleExpr = "0.0008f",
                TexPath = "",
                Sound = 1,
            },
            new Def
            {
                Name = "S-NAV Navigator Ultimate",
                TempName = "nav",
                ObjPath = "GFX/items/navigator",
                InvImgPath = "GFX/items/INVnavigator",
                ImgPath = "GFX/items/navigator",
                ScaleExpr = "0.0008f",
                TexPath = "",
                Sound = 1,
            },
            new Def
            {
                Name = "S-NAV 310 Navigator",
                TempName = "nav",
                ObjPath = "GFX/items/navigator",
                InvImgPath = "GFX/items/INVnavigator",
                ImgPath = "GFX/items/navigator",
                ScaleExpr = "0.0008f",
                TexPath = "",
                Sound = 1,
            },
            new Def
            {
                Name = "Radio Transceiver",
                TempName = "radio",
                ObjPath = "GFX/items/radio",
                InvImgPath = "GFX/items/INVradio",
                ImgPath = "GFX/items/radioHUD",
                ScaleExpr = "0.0010f",
                TexPath = "",
                Sound = 1,
            },
            new Def
            {
                Name = "Radio Transceiver",
                TempName = "fineradio",
                ObjPath = "GFX/items/radio",
                InvImgPath = "GFX/items/INVradio",
                ImgPath = "GFX/items/radioHUD",
                ScaleExpr = "1.0f",
                TexPath = "",
                Sound = 1,
            },
            new Def
            {
                Name = "Radio Transceiver",
                TempName = "veryfineradio",
                ObjPath = "GFX/items/radio",
                InvImgPath = "GFX/items/INVradio",
                ImgPath = "GFX/items/radioHUD",
                ScaleExpr = "1.0f",
                TexPath = "",
                Sound = 1,
            },
            new Def
            {
                Name = "Radio Transceiver",
                TempName = "18vradio",
                ObjPath = "GFX/items/radio",
                InvImgPath = "GFX/items/INVradio",
                ImgPath = "GFX/items/radioHUD",
                ScaleExpr = "1.02f",
                TexPath = "",
                Sound = 1,
            },
            new Def
            {
                Name = "Cigarette",
                TempName = "cigarette",
                ObjPath = "GFX/items/420",
                InvImgPath = "GFX/items/INV420",
                ImgPath = "",
                ScaleExpr = "0.0004f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "Joint",
                TempName = "420s",
                ObjPath = "GFX/items/420",
                InvImgPath = "GFX/items/INV420",
                ImgPath = "",
                ScaleExpr = "0.0004f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "Smelly Joint",
                TempName = "420s",
                ObjPath = "GFX/items/420",
                InvImgPath = "GFX/items/INV420",
                ImgPath = "",
                ScaleExpr = "0.0004f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "Severed Hand",
                TempName = "hand",
                ObjPath = "GFX/items/severedhand",
                InvImgPath = "GFX/items/INVhand",
                ImgPath = "",
                ScaleExpr = "0.04f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "Black Severed Hand",
                TempName = "hand2",
                ObjPath = "GFX/items/severedhand",
                InvImgPath = "GFX/items/INVhand2",
                ImgPath = "",
                ScaleExpr = "0.04f",
                TexPath = "GFX/items/shand2",
                Sound = 2,
            },
            new Def
            {
                Name = "9V Battery",
                TempName = "bat",
                ObjPath = "GFX/items/Battery/Battery",
                InvImgPath = "GFX/items/Battery/INVbattery9v",
                ImgPath = "",
                ScaleExpr = "0.008f",
                TexPath = "",
                Sound = 1,
            },
            new Def
            {
                Name = "18V Battery",
                TempName = "18vbat",
                ObjPath = "GFX/items/Battery/Battery",
                InvImgPath = "GFX/items/Battery/INVbattery18v",
                ImgPath = "",
                ScaleExpr = "0.01f",
                TexPath = "GFX/items/Battery/Battery 18V",
                Sound = 1,
            },
            new Def
            {
                Name = "Strange Battery",
                TempName = "killbat",
                ObjPath = "GFX/items/Battery/Battery",
                InvImgPath = "GFX/items/Battery/INVbattery22900",
                ImgPath = "",
                ScaleExpr = "0.01f",
                TexPath = "GFX/items/Battery/Strange Battery",
                Sound = 1,
            },
            new Def
            {
                Name = "Eyedrops",
                TempName = "fineeyedrops",
                ObjPath = "GFX/items/eyedrops",
                InvImgPath = "GFX/items/INVeyedrops",
                ImgPath = "",
                ScaleExpr = "0.0012f",
                TexPath = "GFX/items/eyedrops",
                Sound = 1,
            },
            new Def
            {
                Name = "Eyedrops",
                TempName = "supereyedrops",
                ObjPath = "GFX/items/eyedrops",
                InvImgPath = "GFX/items/INVeyedrops",
                ImgPath = "",
                ScaleExpr = "0.0012f",
                TexPath = "GFX/items/eyedrops",
                Sound = 1,
            },
            new Def
            {
                Name = "ReVision Eyedrops",
                TempName = "eyedrops",
                ObjPath = "GFX/items/eyedrops",
                InvImgPath = "GFX/items/INVeyedrops",
                ImgPath = "",
                ScaleExpr = "0.0012f",
                TexPath = "GFX/items/eyedrops",
                Sound = 1,
            },
            new Def
            {
                Name = "RedVision Eyedrops",
                TempName = "eyedrops",
                ObjPath = "GFX/items/eyedrops",
                InvImgPath = "GFX/items/INVeyedropsred",
                ImgPath = "",
                ScaleExpr = "0.0012f",
                TexPath = "GFX/items/eyedropsred",
                Sound = 1,
            },
            new Def
            {
                Name = "SCP-714",
                TempName = "scp714",
                ObjPath = "GFX/items/scp714",
                InvImgPath = "GFX/items/INV714",
                ImgPath = "",
                ScaleExpr = "0.3f",
                TexPath = "",
                Sound = 3,
            },
            new Def
            {
                Name = "SCP-1025",
                TempName = "scp1025",
                ObjPath = "GFX/items/scp1025",
                InvImgPath = "GFX/items/INV1025",
                ImgPath = "",
                ScaleExpr = "0.1f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "SCP-513",
                TempName = "scp513",
                ObjPath = "GFX/items/513",
                InvImgPath = "GFX/items/INV513",
                ImgPath = "",
                ScaleExpr = "0.1f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "Clipboard",
                TempName = "clipboard",
                ObjPath = "GFX/items/clipboard",
                InvImgPath = "GFX/items/INVclipboard",
                ImgPath = "",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 1,
            },
            new Def
            {
                Name = "SCP-1123",
                TempName = "1123",
                ObjPath = "GFX/items/HGIB_Skull1",
                InvImgPath = "GFX/items/inv1123",
                ImgPath = "",
                ScaleExpr = "0.015f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "Document SCP-1074",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc1074",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "SCP-1074 Containment Notice",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc_arce",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Night Vision Goggles",
                TempName = "supernv",
                ObjPath = "GFX/items/NVG",
                InvImgPath = "GFX/items/INVsupernightvision",
                ImgPath = "",
                ScaleExpr = "0.02f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "Night Vision Goggles",
                TempName = "nvgoggles",
                ObjPath = "GFX/items/NVG",
                InvImgPath = "GFX/items/INVnightvision",
                ImgPath = "",
                ScaleExpr = "0.02f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "Night Vision Goggles",
                TempName = "finenvgoggles",
                ObjPath = "GFX/items/NVG",
                InvImgPath = "GFX/items/INVveryfinenightvision",
                ImgPath = "",
                ScaleExpr = "0.02f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "Syringe",
                TempName = "syringe",
                ObjPath = "GFX/items/Syringe/syringe",
                InvImgPath = "GFX/items/Syringe/inv",
                ImgPath = "",
                ScaleExpr = "0.005f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "Syringe",
                TempName = "finesyringe",
                ObjPath = "GFX/items/Syringe/syringe",
                InvImgPath = "GFX/items/Syringe/inv",
                ImgPath = "",
                ScaleExpr = "0.005f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "Syringe",
                TempName = "veryfinesyringe",
                ObjPath = "GFX/items/Syringe/syringe",
                InvImgPath = "GFX/items/Syringe/inv",
                ImgPath = "",
                ScaleExpr = "0.005f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "SCP-1499",
                TempName = "scp1499",
                ObjPath = "GFX/items/SCP-1499",
                InvImgPath = "GFX/items/INVscp1499",
                ImgPath = "",
                ScaleExpr = "0.023f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "SCP-1499",
                TempName = "super1499",
                ObjPath = "GFX/items/SCP-1499",
                InvImgPath = "GFX/items/INVscp1499",
                ImgPath = "",
                ScaleExpr = "0.023f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "Emily Ross' Badge",
                TempName = "badge",
                ObjPath = "GFX/items/badge",
                InvImgPath = "GFX/items/INVbadge",
                ImgPath = "GFX/items/badge1",
                ScaleExpr = "0.0001f",
                TexPath = "GFX/items/badge1_tex",
                Sound = 1,
            },
            new Def
            {
                Name = "Lost Key",
                TempName = "key",
                ObjPath = "GFX/items/key",
                InvImgPath = "GFX/items/INV1162_1",
                ImgPath = "",
                ScaleExpr = "0.001f",
                TexPath = "GFX/items/key2",
                Sound = 3,
            },
            new Def
            {
                Name = "Disciplinary Hearing DH-S-4137-17092",
                TempName = "oldpaper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/dh",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Coin",
                TempName = "coin",
                ObjPath = "GFX/items/key",
                InvImgPath = "GFX/items/INVcoin",
                ImgPath = "",
                ScaleExpr = "0.0005f",
                TexPath = "GFX/items/coin",
                Sound = 3,
            },
            new Def
            {
                Name = "Movie Ticket",
                TempName = "ticket",
                ObjPath = "GFX/items/key",
                InvImgPath = "GFX/items/INVticket",
                ImgPath = "GFX/items/ticket",
                ScaleExpr = "0.002f",
                TexPath = "GFX/items/tickettexture",
                Sound = 0,
            },
            new Def
            {
                Name = "Old Badge",
                TempName = "badge",
                ObjPath = "GFX/items/badge",
                InvImgPath = "GFX/items/INVoldbadge",
                ImgPath = "GFX/items/badge2",
                ScaleExpr = "0.0001f",
                TexPath = "GFX/items/badge2_tex",
                Sound = 1,
            },
            new Def
            {
                Name = "Quarter",
                TempName = "25ct",
                ObjPath = "GFX/items/key",
                InvImgPath = "GFX/items/INVcoin",
                ImgPath = "",
                ScaleExpr = "0.0005f",
                TexPath = "GFX/items/coin",
                Sound = 3,
            },
            new Def
            {
                Name = "Wallet",
                TempName = "wallet",
                ObjPath = "GFX/items/wallet",
                InvImgPath = "GFX/items/INVwallet",
                ImgPath = "",
                ScaleExpr = "0.0005f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "SCP-427",
                TempName = "scp427",
                ObjPath = "GFX/items/427",
                InvImgPath = "GFX/items/INVscp427",
                ImgPath = "",
                ScaleExpr = "0.001f",
                TexPath = "",
                Sound = 1,
            },
            new Def
            {
                Name = "Upgraded pill",
                TempName = "scp500death",
                ObjPath = "GFX/items/pill",
                InvImgPath = "GFX/items/INVpill",
                ImgPath = "",
                ScaleExpr = "0.0001f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "Pill",
                TempName = "pill",
                ObjPath = "GFX/items/pill",
                InvImgPath = "GFX/items/INVpillwhite",
                ImgPath = "",
                ScaleExpr = "0.0001f",
                TexPath = "",
                Sound = 2,
            },
            new Def
            {
                Name = "Sticky Note",
                TempName = "paper",
                ObjPath = "GFX/items/note",
                InvImgPath = "GFX/items/INVnote2",
                ImgPath = "GFX/items/note682",
                ScaleExpr = "0.0025f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "The Modular Site Project",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/docMSP",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Research Sector-02 Scheme",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/docmap",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
            new Def
            {
                Name = "Document SCP-427",
                TempName = "paper",
                ObjPath = "GFX/items/paper",
                InvImgPath = "GFX/items/INVpaper",
                ImgPath = "GFX/items/doc427",
                ScaleExpr = "0.003f",
                TexPath = "",
                Sound = 0,
            },
        };
    }
}